### ISSUE TITLE
Does the version ( j2v8 4.7.1 for linux) support ES6 import, new features?

### ISSUE THREAD

**Issue by megharao** [eclipsesource/J2V8#279]
I want to load javascript which is using ES6 import and "new" features. Does j2v8 support ES6?

**Comment by matiwinnetou** [comment]
It uses node 7.4.0 so one needs to check what exact;y V8 version is in this nodejs version.

**Comment by irbull** [comment]
It builds on V8 version `5.4.500.45`. I don't know if this version supports import. If anyone has some time to try this out and post the answer, that would be greatly appreciated.

**Comment by matiwinnetou** [comment]
I am pretty sure: v8 5.4.x does support ES6 imports, in version 6 they already focus on rest spread operator...

https://v8project.blogspot.de/

**Comment by irbull** [comment]
I just tested it, and unfortunately the answer is no.

```
    @Test
    public void testImport() {
        String jsCode = "import * as foo from './foo'\n"
                + "let y = foo.square(5);\n"
                + "y;";
        System.out.println(v8.executeIntegerScript(jsCode));
    }
```
This ails with a compilation error on the symbol `import`. I also found [this](https://www.reddit.com/r/node/comments/43kbcu/cant_use_es6_modules_in_node_v5/) while searching the issue, which appears to state that import / module support is not yet available in V8 5.4. 

As I've often said, we are _bug for bug, feature for feature_ compatible with V8. We can do as much as V8, but no more.
